# Generated by Django 2.2.1 on 2019-11-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_pay_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='airport_transfer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='shillong_transfer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
