# Generated by Django 2.2.1 on 2019-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_auto_20191107_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='airport_transfer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='shillong_transfer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
