# Generated by Django 2.2.1 on 2020-10-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_remove_book_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='drive_train',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='price',
            field=models.IntegerField(default=2999),
            preserve_default=False,
        ),
    ]
