# Generated by Django 2.2.1 on 2020-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20201029_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('cars', models.ManyToManyField(related_name='Region', to='vehicle.Definition')),
            ],
        ),
    ]
