# Generated by Django 2.2.1 on 2020-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
