# Generated by Django 2.2.1 on 2020-11-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_definition_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='car_type',
        ),
    ]
