# Generated by Django 2.2.1 on 2021-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_auto_20201106_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
