# Generated by Django 2.2.1 on 2019-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190305_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='heading',
            field=models.CharField(default='asd', max_length=256),
            preserve_default=False,
        ),
    ]
