# Generated by Django 2.2.1 on 2019-11-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_image_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='heading',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
