# Generated by Django 2.2.1 on 2020-08-04 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_auto_20191117_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('person_dome', models.IntegerField(blank=True, null=True)),
                ('person_tent', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
