# Generated by Django 2.2.1 on 2020-01-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_blogreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreview',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_blog', to='blog.Blog'),
        ),
    ]
