# Generated by Django 2.2.1 on 2019-10-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0021_auto_20191005_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='maps/detail'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='maps/detail')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
    ]
