# Generated by Django 2.2.1 on 2019-11-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0024_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='iconImage',
        ),
    ]
