# Generated by Django 2.2.1 on 2019-11-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0025_remove_map_iconimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='important_to_know',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='map_loc',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='note',
        ),
    ]
