# Generated by Django 2.2.1 on 2019-11-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0026_auto_20191101_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='campfire',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
