# Generated by Django 2.2.1 on 2019-11-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0027_feature_campfire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='good_for_groups',
        ),
    ]
