# Generated by Django 2.2.1 on 2019-11-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0028_remove_amenity_good_for_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='jungle_walk',
            new_name='picnic',
        ),
    ]
