# Generated by Django 2.2.1 on 2019-11-02 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0029_auto_20191102_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCampsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=128)),
                ('bank', models.CharField(max_length=128)),
                ('IFCS', models.CharField(max_length=128)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
