# Generated by Django 2.2.1 on 2019-11-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0030_paymentcampsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='river',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caravan', models.IntegerField(default=0)),
                ('rooftop', models.IntegerField(default=0)),
                ('BYOT', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('book', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
    ]
