# Generated by Django 2.2.1 on 2019-11-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0031_auto_20191102_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='river',
        ),
    ]
