# Generated by Django 2.2.1 on 2019-11-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0032_remove_activity_river'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcampsite',
            old_name='IFCS',
            new_name='IFSC',
        ),
    ]
