# Generated by Django 2.2.1 on 2019-11-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0033_auto_20191102_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='cc_higlight',
        ),
    ]
