# Generated by Django 2.2.1 on 2019-11-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0036_destination_known_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='place',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
