# Generated by Django 2.2.1 on 2019-11-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0037_auto_20191106_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcampsite',
            name='phone',
            field=models.BigIntegerField(default='999999999'),
            preserve_default=False,
        ),
    ]
