# Generated by Django 2.2.1 on 2019-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0038_paymentcampsite_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='starting',
            field=models.IntegerField(default=0),
        ),
    ]
