# Generated by Django 2.2.1 on 2019-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0039_pricing_starting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='starting',
        ),
        migrations.AddField(
            model_name='map',
            name='starting',
            field=models.IntegerField(default=0),
        ),
    ]
