# Generated by Django 2.2.1 on 2019-11-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0040_auto_20191114_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='exp_number',
            field=models.IntegerField(default=1),
        ),
    ]
