# Generated by Django 2.2.1 on 2019-11-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0041_experience_exp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
