# Generated by Django 2.2.1 on 2019-11-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0044_destination_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
