# Generated by Django 2.2.1 on 2021-09-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0046_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='experiences'),
        ),
    ]
