# Generated by Django 2.2.1 on 2021-09-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0047_experiences_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='image5',
        ),
        migrations.AddField(
            model_name='experiences',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='include',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='inclusive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='validity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiences',
            name='what_to_bring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExperiencesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='experiences')),
                ('experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_name', to='destination.Experiences')),
            ],
        ),
    ]
