# Generated by Django 2.2.1 on 2021-09-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0048_auto_20210911_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencesimage',
            name='total_book',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ExperiencesBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(blank=True, max_length=128, null=True)),
                ('camper', models.IntegerField()),
                ('experiences', models.IntegerField()),
                ('campkit', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('igst', models.FloatField(blank=True, null=True)),
                ('convenient', models.FloatField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Experiences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
