# Generated by Django 2.2.1 on 2021-09-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0049_auto_20210912_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencesimage',
            name='total_book',
        ),
        migrations.AddField(
            model_name='experiences',
            name='total_book',
            field=models.IntegerField(default=10),
        ),
    ]
