# Generated by Django 2.2.1 on 2021-09-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0050_auto_20210912_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaning_fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='cleaning_fees',
            field=models.IntegerField(default=0),
        ),
    ]
