# Generated by Django 2.2.1 on 2021-12-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0002_tentcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('name_extended', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('warranty', models.TextField()),
                ('features', models.TextField()),
                ('sleeping_capacity', models.CharField(blank=True, max_length=128, null=True)),
                ('dimentions_closed', models.CharField(blank=True, max_length=128, null=True)),
                ('weight', models.CharField(blank=True, max_length=128, null=True)),
                ('static_weight_capacity', models.CharField(blank=True, max_length=128, null=True)),
                ('minimum_bar_spread', models.CharField(blank=True, max_length=128, null=True)),
                ('base_construction', models.CharField(blank=True, max_length=128, null=True)),
                ('canopy_fabric', models.CharField(blank=True, max_length=128, null=True)),
                ('internal_frame', models.CharField(blank=True, max_length=128, null=True)),
                ('mosquito_screens', models.CharField(blank=True, max_length=128, null=True)),
                ('seasons', models.CharField(blank=True, max_length=128, null=True)),
                ('colors', models.CharField(blank=True, max_length=128, null=True)),
                ('model_number', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='tent')),
                ('tent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tent', to='tent.Tent')),
            ],
        ),
    ]
