# Generated by Django 2.2.1 on 2021-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0003_tent_tentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
