# Generated by Django 2.2.1 on 2021-12-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0004_tent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='main_tent_image',
            field=models.ImageField(blank=True, upload_to='tent'),
        ),
    ]
