# Generated by Django 2.2.1 on 2021-12-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0005_tent_main_tent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tent',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
