# Generated by Django 2.2.1 on 2022-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0006_auto_20211220_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='telescopic_ladder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
