# Generated by Django 2.2.1 on 2022-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0007_tent_telescopic_ladder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentcart',
            name='convenient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tentcart',
            name='coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tentcart',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tentcart',
            name='ladder',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tentcart',
            name='shipping',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
