# Generated by Django 2.2.1 on 2022-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tent', '0008_auto_20220121_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentcart',
            name='tent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
