# Generated by Django 2.2.1 on 2019-10-18 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_remove_book_booked'),
        ('genie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanliness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_tent', models.ImageField(blank=True, upload_to='genie/cleanliness')),
                ('inside_car', models.ImageField(blank=True, upload_to='genie/cleanliness')),
                ('outside_car', models.ImageField(blank=True, upload_to='genie/cleanliness')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Book')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('id2', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('id3', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('id4', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('id5', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Book')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('rear', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('side1', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('side2', models.ImageField(blank=True, upload_to='genie/vehicle_photo')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='Create',
        ),
    ]
