# Generated by Django 2.2.1 on 2019-10-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_auto_20191018_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclephoto',
            old_name='rear',
            new_name='back',
        ),
    ]
